# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.user.role.name
form: ~/Modules/Backend/Models/userrole/fields.yaml
modelClass: Modules\Backend\Models\UserRole
defaultRedirect: backend/userroles

create:
    redirect: backend/userroles/update/:id
    redirectClose: backend/userroles

update:
    redirect: backend/userroles
    redirectClose: backend/userroles
