# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.group.list_title
list: ~/Modules/Backend/Models/usergroup/columns.yaml
modelClass: Modules\Backend\Models\UserGroup
recordUrl: backend/usergroups/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 25
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
