# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.user.name
form: ~/Modules/Backend/Models/user/fields.yaml
modelClass: Modules\Backend\Models\User
defaultRedirect: backend/users

create:
    redirect: backend/users/update/:id
    redirectClose: backend/users

update:
    redirect: backend/users
    redirectClose: backend/users
