# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.list_title
list: ~/Modules/Backend/Models/user/columns.yaml
modelClass: Modules\Backend\Models\User
recordUrl: backend/users/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
# showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
